hadd -f combined_SLep.root data_SEleBlockB1/data_SEleBlockB1_Merged_rootplas.root data_SEleBlockC1/data_SEleBlockC1_Merged_rootplas.root data_SEleBlockD1/data_SEleBlockD1_Merged_rootplas.root data_SMuBlockB1/data_SMuBlockB1_Merged_rootplas.root data_SMuBlockC1/data_SMuBlockC1_Merged_rootplas.root data_SMuBlockD1/data_SMuBlockD1_Merged_rootplas.root

#data_SEleBlockE1/data_SEleBlockE1_Merged_rootplas.root
#data_SEleBlockF1/data_SEleBlockF1_Merged_rootplas.root
#data_SEleBlockF2/data_SEleBlockF2_Merged_rootplas.root
#data_SEleBlockG1/data_SEleBlockG1_Merged_rootplas.root
#data_SEleBlockH1/data_SEleBlockH1_Merged_rootplas.root
#data_SEleBlockH2/data_SEleBlockH2_Merged_rootplas.root
#data_SMuBlockF1/data_SMuBlockF1_Merged_rootplas.root
#data_SMuBlockF2/data_SMuBlockF2_Merged_rootplas.root
#data_SMuBlockG1/data_SMuBlockG1_Merged_rootplas.root
#data_SMuBlockH1/data_SMuBlockH1_Merged_rootplas.root
#data_SMuBlockH2/data_SMuBlockH2_Merged_rootplas.root
